/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BelajarGUI;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Raika Maulana Dwi P
 */
public class Login extends javax.swing.JFrame {
    Icon iconGagal = new javax.swing.ImageIcon(getClass().getResource("/Assets/warning.png"));
    Icon iconSukses = new javax.swing.ImageIcon(getClass().getResource("/Assets/dazai-true.png"));
    Session ses = new Session();
    
    public void placeholder(JTextField textField) {
        Font text = textField.getFont();
        text = text.deriveFont(Font.ITALIC);
        textField.setFont(text);
        textField.setForeground(Color.GRAY);
    }
    
    public void removePlaceholder(JTextField textField) {
        Font text = textField.getFont();
        text = text.deriveFont(Font.PLAIN);
        textField.setFont(text);
        textField.setForeground(Color.BLACK);
    }
    
    public void blackPlaceholder(JTextField textField) {
        Font text = textField.getFont();
        text = text.deriveFont(Font.ITALIC);
        textField.setFont(text);
        textField.setForeground(Color.BLACK);
    }
    
    public void blueBorder (JTextField textField) {
        textField.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(255, 255, 0)));
    }
    
    public void greenBorder (JTextField textField) {
        textField.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(3, 255, 104)));
    }
    
    public void showHide() {
        viewPass1.setVisible(true);
        hidePass1.setVisible(false);
    }
    
    public void placeholderPass() {
        jPasswordField.setText("Masukkan password");
        jPasswordField.setEchoChar((char) 0);
    }
    
    public void sizingImage(javax.swing.JLabel image) {
        Icon icon = image.getIcon();
        if (icon instanceof ImageIcon) {
            ImageIcon imageIcon = (ImageIcon) icon;
            Image img = imageIcon.getImage().getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH);
            image.setIcon(new ImageIcon(img));
        }
    }
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        sizingImage(viewPass1);
        sizingImage(hidePass1);
        sizingImage(kyoukaLogin);
        blueBorder(textFUsername1);
        blueBorder(jPasswordField);
        showHide();
        placeholder(textFUsername1);
        placeholder(jPasswordField);
        textFUsername1.setText("Masukkan username");
        placeholderPass();
        Cursor cursor = Toolkit.getDefaultToolkit().createCustomCursor(new ImageIcon(getClass().getResource("/Assets/cursor-6.png")).getImage(), new Point(0,0), "custom cursor");
        setCursor(cursor);
        if (ses.getUsername().equals("")) {
            return;
        } else {
            textFUsername1.setText(ses.getUsername());
            greenBorder(textFUsername1);
            removePlaceholder(textFUsername1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPass = new javax.swing.JLabel();
        hidePass = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFUsername1 = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        viewPass1 = new javax.swing.JLabel();
        hidePass1 = new javax.swing.JLabel();
        kyoukaLogin = new javax.swing.JLabel();
        butLogin = new buttoncustom.JButtonCustom();
        jPanel2 = new javax.swing.JPanel();

        viewPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewPassMouseClicked(evt);
            }
        });

        hidePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hidePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidePassMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Tugas Pertemuan 9 Raika ");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Assets/logo-unsika.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setText("ID User");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 30));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 30)); // NOI18N
        jLabel2.setText("LOGIN APLIKASI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 28, -1, -1));

        textFUsername1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        textFUsername1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 218, 0), 2));
        textFUsername1.setMargin(new java.awt.Insets(2, 8, 2, 8));
        textFUsername1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFUsername1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFUsername1FocusLost(evt);
            }
        });
        textFUsername1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textFUsername1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textFUsername1MouseExited(evt);
            }
        });
        textFUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFUsername1ActionPerformed(evt);
            }
        });
        jPanel1.add(textFUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 319, 30));

        jPasswordField.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jPasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 218, 0), 2));
        jPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusLost(evt);
            }
        });
        jPasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPasswordFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPasswordFieldMouseExited(evt);
            }
        });
        jPanel1.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 319, 30));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 30));

        viewPass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/view.png"))); // NOI18N
        viewPass1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewPass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewPass1MouseClicked(evt);
            }
        });
        jPanel1.add(viewPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 30, 30));

        hidePass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/hide.png"))); // NOI18N
        hidePass1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hidePass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidePass1MouseClicked(evt);
            }
        });
        jPanel1.add(hidePass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 30, 30));

        kyoukaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/login-image.png"))); // NOI18N
        jPanel1.add(kyoukaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 170, 230));

        butLogin.setText("LOGIN");
        butLogin.setAlignmentY(0.0F);
        butLogin.setColor1(new java.awt.Color(255, 255, 0));
        butLogin.setColor2(new java.awt.Color(3, 255, 104));
        butLogin.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        butLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butLogin.setIconTextGap(15);
        butLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLoginActionPerformed(evt);
            }
        });
        jPanel1.add(butLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 320, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 640, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textFUsername1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFUsername1FocusGained
        // TODO add your handling code here:
        if (textFUsername1.getText().equals("Masukkan username")) {
            textFUsername1.setText("");
            removePlaceholder(textFUsername1);
            greenBorder(textFUsername1);
        } else if (textFUsername1.getText().equals("")) {
            textFUsername1.setText("");
            removePlaceholder(textFUsername1);
            greenBorder(textFUsername1);
        }
    }//GEN-LAST:event_textFUsername1FocusGained

    private void textFUsername1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFUsername1FocusLost
        // TODO add your handling code here:
        if (textFUsername1.getText().equals("")) {
            textFUsername1.setText("Masukkan username");
            placeholder(textFUsername1);
            blueBorder(textFUsername1);
        }
    }//GEN-LAST:event_textFUsername1FocusLost

    private void textFUsername1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFUsername1MouseEntered
        // TODO add your handling code here:
        if (textFUsername1.getText().equals("Masukkan username")) {
            blackPlaceholder(textFUsername1);
        }
    }//GEN-LAST:event_textFUsername1MouseEntered

    private void textFUsername1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFUsername1MouseExited
        // TODO add your handling code here:
        if (textFUsername1.getText().equals("Masukkan username")) {
            placeholder(textFUsername1);
        }
    }//GEN-LAST:event_textFUsername1MouseExited

    private void jPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusGained
        // TODO add your handling code here:
        if(jPasswordField.getText().equals("Masukkan password")) {
            jPasswordField.setText("");
            jPasswordField.setEchoChar('*');
            removePlaceholder(jPasswordField);
            greenBorder(jPasswordField);
        }
    }//GEN-LAST:event_jPasswordFieldFocusGained

    private void jPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusLost
        // TODO add your handling code here:
        if(jPasswordField.getText().equals("")) {
            jPasswordField.setText("Masukkan password");
            jPasswordField.setEchoChar((char) 0);
            placeholder(jPasswordField);
            blueBorder(jPasswordField);
        }
    }//GEN-LAST:event_jPasswordFieldFocusLost

    private void jPasswordFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldMouseEntered
        // TODO add your handling code here:
        if (jPasswordField.getText().equals("Masukkan password")) {
            blackPlaceholder(jPasswordField);
        }
    }//GEN-LAST:event_jPasswordFieldMouseEntered

    private void jPasswordFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldMouseExited
        // TODO add your handling code here:
        if (jPasswordField.getText().equals("Masukkan password")) {
            placeholder(jPasswordField);
        }
    }//GEN-LAST:event_jPasswordFieldMouseExited

    private void viewPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPassMouseClicked
        // TODO add your handling code here:
        if (!jPasswordField.getText().equals("Masukkan password") && !jPasswordField.getText().equals("")) {
            jPasswordField.setEchoChar((char) 0);
            viewPass1.setVisible(false);
            hidePass1.setVisible(true);
        }
    }//GEN-LAST:event_viewPassMouseClicked

    private void hidePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePassMouseClicked
        // TODO add your handling code here:
        if (!jPasswordField.getText().equals("Masukkan password") && !jPasswordField.getText().equals("")) {
            jPasswordField.setEchoChar('*');
            viewPass1.setVisible(true);
            hidePass1.setVisible(false);
        }
    }//GEN-LAST:event_hidePassMouseClicked

    private void viewPass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPass1MouseClicked
        // TODO add your handling code here:
        if (!jPasswordField.getText().equals("Masukkan password") && !jPasswordField.getText().equals("")) {
            jPasswordField.setEchoChar((char) 0);
            viewPass1.setVisible(false);
            hidePass1.setVisible(true);
        }
    }//GEN-LAST:event_viewPass1MouseClicked

    private void hidePass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePass1MouseClicked
        // TODO add your handling code here:
        if (!jPasswordField.getText().equals("Masukkan password") && !jPasswordField.getText().equals("")) {
            jPasswordField.setEchoChar('*');
            viewPass1.setVisible(true);
            hidePass1.setVisible(false);
        }
    }//GEN-LAST:event_hidePass1MouseClicked

    private void textFUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFUsername1ActionPerformed

    private void butLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLoginActionPerformed

        String usn = textFUsername1.getText();
        String password = String.valueOf(jPasswordField.getPassword());
        if (usn.equals("Masukkan username") && password.equals("Masukkan password")) {
            JOptionPane.showMessageDialog(null, "<html><b>Username</b> dan <b>Password</b> kosong</html>", "✿ PESAN ✿", JOptionPane.WARNING_MESSAGE, iconGagal);
        } else if (usn.equals("Masukkan username") && !(password.equals("Masukkan password"))) {
            JOptionPane.showMessageDialog(null, "<html><b>Username</b> kosong</html>", "✿ PESAN ✿", JOptionPane.WARNING_MESSAGE, iconGagal);
        } else if (password.equals("Masukkan password") && !(usn.equals("Masukkan username"))) {
            JOptionPane.showMessageDialog(null, "<html><b>Password</b> kosong</html>", "✿ PESAN ✿", JOptionPane.WARNING_MESSAGE, iconGagal);
        } else {
            try {
                if ((!usn.equals("")) && 
                        (String.valueOf(jPasswordField.getPassword()).equals("yuuki"))) {
                    JOptionPane.showMessageDialog(null, "<html>Selamat Datang <b>'" + usn + "'</b></html>", "✿ PESAN ✿", JOptionPane.INFORMATION_MESSAGE, iconSukses);
                    ses.setUsername(usn);
                    new MenuUtama().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "<html><b>Username</b> atau <b>Password</b> salah</html>", "✿ PESAN ✿", JOptionPane.WARNING_MESSAGE, iconGagal);
                    jPasswordField.setText("");
                    placeholder(textFUsername1);
                    placeholderPass();
                    blueBorder(textFUsername1);
                    blueBorder(jPasswordField);
                    placeholder(jPasswordField);
                    textFUsername1.setText("Masukkan username");
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, "Error", "✿ PESAN ✿", JOptionPane.WARNING_MESSAGE, iconGagal);
            }
        }
    }//GEN-LAST:event_butLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private buttoncustom.JButtonCustom butLogin;
    private javax.swing.JLabel hidePass;
    private javax.swing.JLabel hidePass1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JLabel kyoukaLogin;
    private javax.swing.JTextField textFUsername1;
    private javax.swing.JLabel viewPass;
    private javax.swing.JLabel viewPass1;
    // End of variables declaration//GEN-END:variables
}
