/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BelajarGUI;

import Kalkulator.Kalkulator;
import PenentuJumlahHari.PenentuJumlahHari;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class MenuUtama extends javax.swing.JFrame {
    Icon iconKonfirm = new javax.swing.ImageIcon(getClass().getResource("/Assets/iconKonfirm.png"));
    private String username = Session.getUsername();
    Login log = new Login();
    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        labelUser.setText("<html>Halo, <b>" + username + "</b></html>");
        Cursor cursor = Toolkit.getDefaultToolkit().createCustomCursor(new ImageIcon(getClass().getResource("/Assets/cursor-6.png")).getImage(), new Point(0,0), "custom cursor");
        setCursor(cursor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label = new javax.swing.JPanel();
        labelUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnKalkulator = new javax.swing.JPanel();
        labKalkulator = new javax.swing.JLabel();
        pnJumlahHari = new javax.swing.JPanel();
        labJumlahHari = new javax.swing.JLabel();
        pnOperasiPertambahan = new javax.swing.JPanel();
        labOperasiPertambahan = new javax.swing.JLabel();
        pnNilaiMahasiswa = new javax.swing.JPanel();
        labNilaiMahasiswa = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama PT9");
        setMinimumSize(new java.awt.Dimension(665, 326));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(665, 326));

        label.setBackground(new java.awt.Color(255, 255, 153));

        labelUser.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        labelUser.setText("Username Session");

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setText("PBO Pertemuan 9 GUI");

        javax.swing.GroupLayout labelLayout = new javax.swing.GroupLayout(label);
        label.setLayout(labelLayout);
        labelLayout.setHorizontalGroup(
            labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, labelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelUser)
                .addGap(71, 71, 71))
        );
        labelLayout.setVerticalGroup(
            labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUser)
                    .addComponent(jLabel1))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 153), 4));

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MENU");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnKalkulator.setBackground(new java.awt.Color(204, 255, 255));
        pnKalkulator.setMinimumSize(new java.awt.Dimension(213, 35));

        labKalkulator.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        labKalkulator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labKalkulator.setText("Kalkulator");
        labKalkulator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labKalkulatorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labKalkulatorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labKalkulatorMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnKalkulatorLayout = new javax.swing.GroupLayout(pnKalkulator);
        pnKalkulator.setLayout(pnKalkulatorLayout);
        pnKalkulatorLayout.setHorizontalGroup(
            pnKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labKalkulator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnKalkulatorLayout.setVerticalGroup(
            pnKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labKalkulator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        pnJumlahHari.setBackground(new java.awt.Color(255, 204, 255));
        pnJumlahHari.setMinimumSize(new java.awt.Dimension(213, 35));

        labJumlahHari.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        labJumlahHari.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labJumlahHari.setText("Penentu Jumlah Hari");
        labJumlahHari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labJumlahHariMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labJumlahHariMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labJumlahHariMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnJumlahHariLayout = new javax.swing.GroupLayout(pnJumlahHari);
        pnJumlahHari.setLayout(pnJumlahHariLayout);
        pnJumlahHariLayout.setHorizontalGroup(
            pnJumlahHariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labJumlahHari, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
        );
        pnJumlahHariLayout.setVerticalGroup(
            pnJumlahHariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labJumlahHari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnOperasiPertambahan.setBackground(new java.awt.Color(255, 204, 204));
        pnOperasiPertambahan.setMinimumSize(new java.awt.Dimension(213, 35));

        labOperasiPertambahan.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        labOperasiPertambahan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labOperasiPertambahan.setText("Operasi Pertambahan");
        labOperasiPertambahan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labOperasiPertambahanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labOperasiPertambahanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labOperasiPertambahanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnOperasiPertambahanLayout = new javax.swing.GroupLayout(pnOperasiPertambahan);
        pnOperasiPertambahan.setLayout(pnOperasiPertambahanLayout);
        pnOperasiPertambahanLayout.setHorizontalGroup(
            pnOperasiPertambahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labOperasiPertambahan, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
        );
        pnOperasiPertambahanLayout.setVerticalGroup(
            pnOperasiPertambahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labOperasiPertambahan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        pnNilaiMahasiswa.setBackground(new java.awt.Color(204, 255, 204));
        pnNilaiMahasiswa.setMinimumSize(new java.awt.Dimension(213, 35));

        labNilaiMahasiswa.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        labNilaiMahasiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labNilaiMahasiswa.setText("Penentu Nilai Mahasiswa");
        labNilaiMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labNilaiMahasiswaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labNilaiMahasiswaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labNilaiMahasiswaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnNilaiMahasiswaLayout = new javax.swing.GroupLayout(pnNilaiMahasiswa);
        pnNilaiMahasiswa.setLayout(pnNilaiMahasiswaLayout);
        pnNilaiMahasiswaLayout.setHorizontalGroup(
            pnNilaiMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labNilaiMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
        );
        pnNilaiMahasiswaLayout.setVerticalGroup(
            pnNilaiMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labNilaiMahasiswa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnOperasiPertambahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnKalkulator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnJumlahHari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnNilaiMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnJumlahHari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnKalkulator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnOperasiPertambahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnNilaiMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));

        btnLogout.setBackground(new java.awt.Color(255, 255, 204));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setText("Raika Maulana Dwi Putra | 2410631170100 | 3B Informatika");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(39, 39, 39))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(262, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(10, 10, 10))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jLabel2)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(115, 115, 115))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Yakin ingin keluar?", "Konfirmasi Keluar Aplikasi", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, iconKonfirm);
        if (result == JOptionPane.NO_OPTION) {
            return;
        } else if (result == JOptionPane.YES_OPTION) {
            MenuUtama mu = new MenuUtama();
            mu.setVisible(false);
            this.dispose();
            log.setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void labNilaiMahasiswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labNilaiMahasiswaMouseEntered
        pnNilaiMahasiswa.setBackground(new Color(153,255,153));
    }//GEN-LAST:event_labNilaiMahasiswaMouseEntered

    private void labNilaiMahasiswaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labNilaiMahasiswaMouseExited
        pnNilaiMahasiswa.setBackground(new Color(204,255,204));
    }//GEN-LAST:event_labNilaiMahasiswaMouseExited

    private void labNilaiMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labNilaiMahasiswaMouseClicked
        pnNilaiMahasiswa.setBackground(new Color(102,255,102));
        MenuUtama mu = new MenuUtama();
        mu.setVisible(false);
        this.dispose();
        AplikasiPenentuNilaiMahasiswa apn = new AplikasiPenentuNilaiMahasiswa();
        apn.setVisible(true);
    }//GEN-LAST:event_labNilaiMahasiswaMouseClicked

    private void labOperasiPertambahanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labOperasiPertambahanMouseClicked
        pnOperasiPertambahan.setBackground(new Color(255,102,102));
        MenuUtama mu = new MenuUtama();
        mu.setVisible(false);
        this.dispose();
        OperasiPertambahan2Angka opa = new OperasiPertambahan2Angka();
        opa.setVisible(true);
    }//GEN-LAST:event_labOperasiPertambahanMouseClicked

    private void labOperasiPertambahanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labOperasiPertambahanMouseEntered
        pnOperasiPertambahan.setBackground(new Color(255,153,153));
    }//GEN-LAST:event_labOperasiPertambahanMouseEntered

    private void labOperasiPertambahanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labOperasiPertambahanMouseExited
        pnOperasiPertambahan.setBackground(new Color(255,204,204));
    }//GEN-LAST:event_labOperasiPertambahanMouseExited

    private void labKalkulatorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labKalkulatorMouseEntered
        pnKalkulator.setBackground(new Color(153,255,255));
    }//GEN-LAST:event_labKalkulatorMouseEntered

    private void labKalkulatorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labKalkulatorMouseExited
        pnKalkulator.setBackground(new Color(204,255,255));
    }//GEN-LAST:event_labKalkulatorMouseExited

    private void labKalkulatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labKalkulatorMouseClicked
        pnKalkulator.setBackground(new Color(102,255,255));
        MenuUtama mu = new MenuUtama();
        mu.setVisible(false);
        this.dispose();
        Kalkulator kal = new Kalkulator();
        kal.setVisible(true);
    }//GEN-LAST:event_labKalkulatorMouseClicked

    private void labJumlahHariMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labJumlahHariMouseEntered
        pnJumlahHari.setBackground(new Color(255,152,255));
    }//GEN-LAST:event_labJumlahHariMouseEntered

    private void labJumlahHariMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labJumlahHariMouseExited
        pnJumlahHari.setBackground(new Color(255,204,255));
    }//GEN-LAST:event_labJumlahHariMouseExited

    private void labJumlahHariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labJumlahHariMouseClicked
        pnJumlahHari.setBackground(new Color(255,102,255));
        MenuUtama mu = new MenuUtama();
        mu.setVisible(false);
        this.dispose();
        PenentuJumlahHari pjh = new PenentuJumlahHari();
        pjh.setVisible(true);
    }//GEN-LAST:event_labJumlahHariMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labJumlahHari;
    private javax.swing.JLabel labKalkulator;
    private javax.swing.JLabel labNilaiMahasiswa;
    private javax.swing.JLabel labOperasiPertambahan;
    private javax.swing.JPanel label;
    private javax.swing.JLabel labelUser;
    private javax.swing.JPanel pnJumlahHari;
    private javax.swing.JPanel pnKalkulator;
    private javax.swing.JPanel pnNilaiMahasiswa;
    private javax.swing.JPanel pnOperasiPertambahan;
    // End of variables declaration//GEN-END:variables
}
